[package]
name = "cacophony_text"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-ini = "0.18"
tts = "0.25.1"
hashbrown = "0.13.2"
csv = "1.2.1"
miniquad = "0.3"

[dependencies.cacophony_core]
path = "../cacophony_core"
