[workspace]
members = ["audio", "common", "input", "io", "render", "text"]

[workspace.package]
version = "0.1.0"
authors = ["Esther Alter <subalterngames@gmail.com>"]
description = "ASCII-esque pseudo-MIDI sequencer"
documentation = "https://github.com/subalterngames/cacophony"
edition = "2021"

[workspace.dependencies]
serde_json = "1.0"
rust-ini = "0.18"
directories = "5.0.0"
time = "0.3.21"
midir = "0.9.1"
crossbeam-channel = "0.5.8"
csv = "1.2.1"
cpal = "0.13.1"
hound = "3.5.0"
id3 = "1.7.0"
mp3lame-encoder = "0.1.2"
chrono = "0.4.26"
ghakuf = "0.5.6"
vorbis-encoder = "0.1.4"
oggvorbismeta = "0.1.0"
strum = "0.24"
strum_macros = "0.24"
edit = "0.1.4"
regex = "1.9.1"
imageproc = "0.23.0"
image = "0.24.6"
rusttype = "0.9.3"

[workspace.dependencies.hashbrown]
version = "0.13.2"
features = ["serde"]

[workspace.dependencies.serde]
version = "1.0.153"
default-features = false
features = ["derive"]

[workspace.dependencies.macroquad]
version = "0.4.1"
default-features = false
features = []

[workspace.dependencies.oxisynth]
version = "0.0.3"
features = ["sf3"]
git = "https://github.com/PolyMeilex/OxiSynth.git"
branch = "master"

[workspace.dependencies.tts]
version = "0.25.5"
default-features = false
features = ["speech_dispatcher_0_9"]

[package]
name = "cacophony"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[dependencies]
macroquad = { workspace = true }

[dependencies.audio]
path = "audio"

[dependencies.common]
path = "common"

[dependencies.input]
path = "input"

[dependencies.io]
path = "io"

[dependencies.render]
path = "render"

[dependencies.text]
path = "text"