[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
edit = "0.1.4"

[dependencies.audio]
path = "../audio"

[dependencies.common]
path = "../common"

[dependencies.input]
path = "../input"

[dependencies.text]
path = "../text"