[package]
name = "cacophony_core"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = "0.24"
strum_macros = "0.24"
fraction = "0.13.1"
serde_json = "1.0"
rust-ini = "0.18"

[dependencies.serde]
version = "1.0.153"
features = ["derive"]