[package]
name = "text"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.9.1"

[dependencies.common]
path = "../common"

[dependencies.input]
path = "../input"

[dependencies.tts]
version = "0.25.5"
default-features = false
features = ["speech_dispatcher_0_9"]
