name: linux

on:
  workflow_dispatch:
    inputs:
      version:
        description: Build version
        required: True

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
      - name: cargo build
        run: cargo build --release
      - name: Create release directory
        run: mkdir -p cacophony/cacophony/data
      - name: Copy executable
        run: cp cacophony/target/release/cacophony cacophony/cacophony
      - name: Copy data/
        run: cp -R cacophony/data cacophony/cacophony/data
      - name: Download butler
        run: wget -O butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
      - name: Unzip butler
        run: unzip butler.zip
      - run: chmod +x butler
      - name: butler login
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler login
      - name: butler push
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push cacophony/cacophony subalterngames/cacophony:linux --userversion=${{ inputs.version }}
