name: macos

on:
  workflow_dispatch:
    inputs:
      version:
        description: Build version
        required: True

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
      - name: Install cargo bundle
        run: cargo install cargo-bundle
      - name: cargo bundle
        run: cargo bundle --release
      - name: Download butler
        run: wget -O butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default
      - name: Unzip butler
        run: unzip butler.zip
      - run: chmod +x butler
      - name: butler login
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler login
      - name: butler push
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: ./butler push cacophony/target/release/Cacophony.app subalterngames/cacophony:macos --userversion=${{ inputs.version }}
