name: Build and run

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "doc/**"
      - ".vscode/**"
      - "html/**"
      - "data/**"
      - "promo/**"
      - "py/**"
      - "**.md"
jobs:
  ubuntu:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            version: 20
            feature: speech_dispatcher_0_9
          - os: ubuntu-22.04
            version: 22
            feature: speech_dispatcher_0_11
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - name: apt update
          run: sudo apt-get update
        - name: install
          run: sudo apt install clang libspeechd-dev pkg-config libssl-dev alsa librust-alsa-sys-dev
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - name: Run and quit
          run: cargo run --release --features ${{ matrix.feature }} -- -q
  macos:
    strategy:
        matrix:
          include:
            - os: macos-11
              version: 11
            - os: macos-12
              version: 12
            - os: macos-13
              version: 13
            - os: macos-14
              version: 14
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - name: Install Rust
          uses: dtolnay/rust-toolchain@stable
          with:
            toolchain: stable
        - name: Run and quit
          run: cargo run --release -- -q
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Run and quit
        run: cargo run --release -- -q
